services:
  postgres:
    image: postgres:16-alpine
    container_name: genui-postgres
    environment:
      POSTGRES_USER: genui
      POSTGRES_PASSWORD: genui123
      POSTGRES_DB: questionnaire
    ports:
      - "10000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - genui-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U genui"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: genui-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@genui.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - genui-network

networks:
  genui-network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
